### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by nailtonvital** [KillovSky/Trendings#1]
When I try search Brazil this error appers:
```
C:\Users\Allan\Documents\GitHub\keiko\server\node_modules\@killovsky\trendings\index.js:172
                        g.trend = decodeURIComponent(g.trend);
                                  ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Users\Allan\Documents\GitHub\keiko\server\node_modules\@killovsky\trendings\index.js:172:35
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\Allan\Documents\GitHub\keiko\server\node_modules\@killovsky\trendings\index.js:170:26)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Removing these lines works well:
``` js
body.forEach(function (g) {
     g.trend = decodeURIComponent(g.trend);
     g.count = decodeURIComponent(g.count);
});
```

**Comment by KillovSky** [comment]
Hello, this seems to be a BUG caused by some "unreadable" character inside the body after parsing, I will try to find it and make a correction patch.

Removing these lines will work, but it will not decode any URI values such as Russian alphabet or ASCII characters.

Edit: I found, this is caused by `g.trend` passing a `%`, which is not readable by the `decodeURI`, I will send the fix after creating additional security parameters.

For now, you can use this:

```javascript
g.trend = decodeURIComponent(g.trend.replace(/%/gi, ""))
```

**Comment by KillovSky** [comment]
You should be able to use it now.

## Release 1.0.2

------ EN ------
- Fixed the module not working properly.
- Error: Cannot parse text due to reserved character.
- Fix: Added 'encodeURIComponent' before 'decodeURIComponent' and inserted a new 'Try-Catch' block.
- New: '.gitignore', '.gitattributes' and a function to return module 'environment' details such as used functions and more.

------ PT-BR ------
- Corrigido erro que fazia o módulo não funcionar adequadamente.
- Erro: Falha no parse do texto devido a um caractere reservado.
- Correção: Adicionado 'encodeURIComponent' antes de 'decodeURIComponent' e inserido um novo bloco 'Try-Catch'.
- Novo: '.gitignore', '.gitattributes' e uma função para retornar detalhes do 'ambiente' do módulo, como funções usadas e mais.
